import { styled } from '@mui/material/styles'
import ReactMarkdown from 'react-markdown'

/**
 * MarkdownDisplay
 * 
 * A styled wrapper for ReactMarkdown that applies Material Design 3 typography
 * and colors to standard HTML elements generated by the markdown parser.
 */
export const MarkdownDisplay = styled('div')(({ theme }) => ({
  color: theme.palette.text.primary,
  fontSize: '0.875rem',
  lineHeight: 1.6,

  // Paragraphs
  '& p': {
    marginTop: 0,
    marginBottom: theme.spacing(1.5),
    '&:last-child': {
      marginBottom: 0,
    },
  },

  // Headings
  '& h1, & h2, & h3, & h4, & h5, & h6': {
    color: theme.palette.text.primary,
    fontWeight: 600,
    marginTop: theme.spacing(3),
    marginBottom: theme.spacing(1.5),
    lineHeight: 1.2,
  },
  '& h1': { fontSize: '1.5rem' },
  '& h2': { fontSize: '1.25rem' },
  '& h3': { fontSize: '1.1rem' },

  // Links
  '& a': {
    color: theme.palette.primary.main,
    textDecoration: 'none',
    '&:hover': {
      textDecoration: 'underline',
    },
  },

  // Lists
  '& ul, & ol': {
    marginTop: 0,
    marginBottom: theme.spacing(1.5),
    paddingLeft: theme.spacing(3),
  },
  '& li': {
    marginBottom: theme.spacing(0.5),
  },

  // Code
  '& code': {
    fontFamily: 'var(--font-mono, Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace)',
    backgroundColor: theme.palette.action.hover,
    padding: '2px 4px',
    borderRadius: theme.shape.borderRadius / 4, // ~4px usually
    fontSize: '0.85em',
  },
  '& pre': {
    margin: theme.spacing(1.5, 0),
    padding: theme.spacing(2),
    backgroundColor: theme.palette.action.hover,
    borderRadius: theme.shape.borderRadius,
    overflow: 'auto',
    '& code': {
      backgroundColor: 'transparent',
      padding: 0,
    },
  },

  // Blockquotes
  '& blockquote': {
    margin: theme.spacing(1.5, 0),
    paddingLeft: theme.spacing(2),
    borderLeft: `4px solid ${theme.palette.divider}`,
    color: theme.palette.text.secondary,
    fontStyle: 'italic',
  },

  // Tables
  '& table': {
    width: '100%',
    borderCollapse: 'collapse',
    marginBottom: theme.spacing(2),
  },
  '& th, & td': {
    padding: theme.spacing(1),
    borderBottom: `1px solid ${theme.palette.divider}`,
    textAlign: 'left',
  },
  '& th': {
    fontWeight: 600,
    color: theme.palette.text.primary,
  },
}))

// Helper component if you want to pass children directly as markdown string
export const Markdown = ({ children }: { children: string }) => {
  return (
    <MarkdownDisplay>
      <ReactMarkdown>{children}</ReactMarkdown>
    </MarkdownDisplay>
  )
}
